; Auto-generated. Do not edit!


(cl:in-package turtlebot3_example-msg)


;//! \htmlinclude turtlebot3Goal.msg.html

(cl:defclass <turtlebot3Goal> (roslisp-msg-protocol:ros-message)
  ((goal
    :reader goal
    :initarg :goal
    :type geometry_msgs-msg:Vector3
    :initform (cl:make-instance 'geometry_msgs-msg:Vector3)))
)

(cl:defclass turtlebot3Goal (<turtlebot3Goal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <turtlebot3Goal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'turtlebot3Goal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name turtlebot3_example-msg:<turtlebot3Goal> is deprecated: use turtlebot3_example-msg:turtlebot3Goal instead.")))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <turtlebot3Goal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader turtlebot3_example-msg:goal-val is deprecated.  Use turtlebot3_example-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <turtlebot3Goal>) ostream)
  "Serializes a message object of type '<turtlebot3Goal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <turtlebot3Goal>) istream)
  "Deserializes a message object of type '<turtlebot3Goal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<turtlebot3Goal>)))
  "Returns string type for a message object of type '<turtlebot3Goal>"
  "turtlebot3_example/turtlebot3Goal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'turtlebot3Goal)))
  "Returns string type for a message object of type 'turtlebot3Goal"
  "turtlebot3_example/turtlebot3Goal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<turtlebot3Goal>)))
  "Returns md5sum for a message object of type '<turtlebot3Goal>"
  "8ad3bd0e46ff6777ce7cd2fdd945cb9e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'turtlebot3Goal)))
  "Returns md5sum for a message object of type 'turtlebot3Goal"
  "8ad3bd0e46ff6777ce7cd2fdd945cb9e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<turtlebot3Goal>)))
  "Returns full string definition for message of type '<turtlebot3Goal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the action goal message~%geometry_msgs/Vector3 goal~%~%================================================================================~%MSG: geometry_msgs/Vector3~%# This represents a vector in free space. ~%# It is only meant to represent a direction. Therefore, it does not~%# make sense to apply a translation to it (e.g., when applying a ~%# generic rigid transformation to a Vector3, tf2 will only apply the~%# rotation). If you want your data to be translatable too, use the~%# geometry_msgs/Point message instead.~%~%float64 x~%float64 y~%float64 z~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'turtlebot3Goal)))
  "Returns full string definition for message of type 'turtlebot3Goal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the action goal message~%geometry_msgs/Vector3 goal~%~%================================================================================~%MSG: geometry_msgs/Vector3~%# This represents a vector in free space. ~%# It is only meant to represent a direction. Therefore, it does not~%# make sense to apply a translation to it (e.g., when applying a ~%# generic rigid transformation to a Vector3, tf2 will only apply the~%# rotation). If you want your data to be translatable too, use the~%# geometry_msgs/Point message instead.~%~%float64 x~%float64 y~%float64 z~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <turtlebot3Goal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <turtlebot3Goal>))
  "Converts a ROS message object to a list"
  (cl:list 'turtlebot3Goal
    (cl:cons ':goal (goal msg))
))
